name: Ruff + Mypy + Hassfest

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install ruff
      - name: Run Ruff
        run: ruff check custom_components/usgs_quakes/

  mypy:
    name: Mypy Type Check
    runs-on: ubuntu-latest
    env:
      MYPYPATH: .

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install mypy + stubs
        run: pip install mypy types-setuptools types-pyyaml types-requests
      - name: Run Mypy
        run: mypy --config-file mypy.ini

  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
